
Loading dataset...
Loaded data : 93389
batch_size = 16
learning rate = 0.0001
train_size = 74711
test_size = 18678
Data load complete!
Initializing model....
Initialize complete!!
Epoch 1
Traceback (most recent call last):
  File "Dilated_conv_vae_main.py", line 145, in <module>
    state, train_loss = train_step(state, x, rng)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 687, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 208, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 257, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 302, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2188, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2138, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "Dilated_conv_vae_main.py", line 68, in train_step
    loss, grads = grad_fn(state.params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 1071, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 2516, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 133, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 122, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 802, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "Dilated_conv_vae_main.py", line 63, in loss_fn
    mse_loss = ((recon_x - jnp.expand_dims(x, axis=-1))**2).mean()
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 576, in __sub__
    def __sub__(self, other): return self.aval._sub(self, other)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py", line 4639, in deferring_binary_op
    return binary_op(*args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 339, in process_call
    result = call_primitive.bind(_update_annotation(f_jvp, f.in_type, which_nz),
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 267, in process_call
    out = primitive.bind(_update_annotation_known(f_, f.in_type, in_knowns),
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 1843, in process_call
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(f, self.main, debug_info=dbg)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2138, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/ufuncs.py", line 69, in <lambda>
    fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py", line 448, in sub
    return sub_p.bind(x, y)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 324, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 327, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 308, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py", line 2120, in _sub_jvp
    primal_out = sub(x, y)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py", line 448, in sub
    return sub_p.bind(x, y)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 324, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 327, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 1817, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 1821, in default_process_primitive
    out_avals, effects = primitive.abstract_eval(*avals, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 360, in abstract_eval_
    return abstract_eval(*args, **kwargs), no_effects
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/utils.py", line 66, in standard_abstract_eval
    return core.ShapedArray(shape_rule(*avals, **kwargs),
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py", line 1514, in _broadcasting_shape_rule
    raise TypeError(f'{name} got incompatible shapes for broadcasting: '
jax._src.traceback_util.UnfilteredStackTrace: TypeError: sub got incompatible shapes for broadcasting: (16, 64, 1824, 1), (16, 48, 1876, 1).
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "Dilated_conv_vae_main.py", line 145, in <module>
    state, train_loss = train_step(state, x, rng)
  File "Dilated_conv_vae_main.py", line 68, in train_step
    loss, grads = grad_fn(state.params)
  File "Dilated_conv_vae_main.py", line 63, in loss_fn
    mse_loss = ((recon_x - jnp.expand_dims(x, axis=-1))**2).mean()
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py", line 4639, in deferring_binary_op
    return binary_op(*args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/ufuncs.py", line 69, in <lambda>
    fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))
TypeError: sub got incompatible shapes for broadcasting: (16, 64, 1824, 1), (16, 48, 1876, 1).
Traceback (most recent call last):
  File "Dilated_conv_vae_main.py", line 145, in <module>
    state, train_loss = train_step(state, x, rng)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 687, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 208, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 257, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 302, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2188, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2138, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "Dilated_conv_vae_main.py", line 68, in train_step
    loss, grads = grad_fn(state.params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 1071, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 2516, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 133, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 122, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 802, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "Dilated_conv_vae_main.py", line 63, in loss_fn
    mse_loss = ((recon_x - jnp.expand_dims(x, axis=-1))**2).mean()
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 576, in __sub__
    def __sub__(self, other): return self.aval._sub(self, other)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py", line 4639, in deferring_binary_op
    return binary_op(*args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 339, in process_call
    result = call_primitive.bind(_update_annotation(f_jvp, f.in_type, which_nz),
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 267, in process_call
    out = primitive.bind(_update_annotation_known(f_, f.in_type, in_knowns),
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 1843, in process_call
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(f, self.main, debug_info=dbg)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2138, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/ufuncs.py", line 69, in <lambda>
    fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py", line 448, in sub
    return sub_p.bind(x, y)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 324, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 327, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 308, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py", line 2120, in _sub_jvp
    primal_out = sub(x, y)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py", line 448, in sub
    return sub_p.bind(x, y)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 324, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 327, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 1817, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 1821, in default_process_primitive
    out_avals, effects = primitive.abstract_eval(*avals, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 360, in abstract_eval_
    return abstract_eval(*args, **kwargs), no_effects
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/utils.py", line 66, in standard_abstract_eval
    return core.ShapedArray(shape_rule(*avals, **kwargs),
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py", line 1514, in _broadcasting_shape_rule
    raise TypeError(f'{name} got incompatible shapes for broadcasting: '
jax._src.traceback_util.UnfilteredStackTrace: TypeError: sub got incompatible shapes for broadcasting: (16, 64, 1824, 1), (16, 48, 1876, 1).
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "Dilated_conv_vae_main.py", line 145, in <module>
    state, train_loss = train_step(state, x, rng)
  File "Dilated_conv_vae_main.py", line 68, in train_step
    loss, grads = grad_fn(state.params)
  File "Dilated_conv_vae_main.py", line 63, in loss_fn
    mse_loss = ((recon_x - jnp.expand_dims(x, axis=-1))**2).mean()
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py", line 4639, in deferring_binary_op
    return binary_op(*args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/ufuncs.py", line 69, in <lambda>
    fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))
TypeError: sub got incompatible shapes for broadcasting: (16, 64, 1824, 1), (16, 48, 1876, 1).