
Loading dataset...
Loaded data : 62235
batch_size = 128
learning rate = 0.0001
train_size = 49788
test_size = 12447
Data load complete!
Initializing model....
Initialize complete!!
Epoch 1
step : 5/389, train_loss : 89594.6484375, test_loss : 79228.8671875
CVAE_main.py:154: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "figsize" which is no longer supported as of 3.3 and will become an error in 3.6
  plt.savefig('recon.png', figsize=(16, 16))
CVAE_main.py:156: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "figsize" which is no longer supported as of 3.3 and will become an error in 3.6

























epoch 1 - average loss - train : 48513.3125, test : 48434.1953125515625
Epoch 2
























epoch 2 - average loss - train : 43968.42578125, test : 43989.886718755
Epoch 3
























epoch 3 - average loss - train : 43814.1484375, test : 43837.3164062555
Epoch 4
























epoch 4 - average loss - train : 43650.03515625, test : 43669.417968755
Epoch 5

























epoch 5 - average loss - train : 43422.5078125, test : 43444.7812575255
Epoch 6

























epoch 6 - average loss - train : nan, test : nannnoss : 44632.464843755
Epoch 7

























epoch 7 - average loss - train : nan, test : nann
Epoch 8

























epoch 8 - average loss - train : nan, test : nann
Epoch 9


























epoch 9 - average loss - train : nan, test : nann
Epoch 10

























epoch 10 - average loss - train : nan, test : nan
Epoch 11

























epoch 11 - average loss - train : nan, test : nan
Epoch 12


























epoch 12 - average loss - train : nan, test : nan
Epoch 13


























epoch 13 - average loss - train : nan, test : nan
Epoch 14
Traceback (most recent call last):
  File "CVAE_main.py", line 156, in <module>
    plt.savefig('x.png', figsize=(16, 16))
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 978, in savefig
    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 2060, in draw_idle
    self.draw(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 2845, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 3091, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 646, in draw
    im, l, b, trans = self.make_image(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 956, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 516, in _make_image
    out_alpha = _resample(self, mask, out_shape, t, resample=True)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 193, in _resample
    _image.resample(data, out, transform,
KeyboardInterrupt
Traceback (most recent call last):
  File "CVAE_main.py", line 156, in <module>
    plt.savefig('x.png', figsize=(16, 16))
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 978, in savefig
    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 2060, in draw_idle
    self.draw(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 2845, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 3091, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 646, in draw
    im, l, b, trans = self.make_image(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 956, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 516, in _make_image
    out_alpha = _resample(self, mask, out_shape, t, resample=True)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 193, in _resample
    _image.resample(data, out, transform,
KeyboardInterrupt