
Loading dataset...
Loaded data : 93389
batch_size = 16
learning rate = 0.0001
train_size = 74711
test_size = 18678
Data load complete!
Initializing model....
Initialize complete!!
Epoch 1
Traceback (most recent call last):
  File "Conv2d_VAE_main_bce_loss.py", line 143, in <module>
    wandb.log({'train_loss' : train_loss, 'test_loss' : test_loss, 'bce_loss':bce_loss, 'kld_loss':kld_loss})
NameError: name 'bce_loss' is not defined
Traceback (most recent call last):
  File "Conv2d_VAE_main_bce_loss.py", line 143, in <module>
    wandb.log({'train_loss' : train_loss, 'test_loss' : test_loss, 'bce_loss':bce_loss, 'kld_loss':kld_loss})
NameError: name 'bce_loss' is not defined