
Epoch 1

  1%|▋                                                 | 4/305 [00:17<12:41,  2.53s/it]




















































































Pre train complete!
Linear evalutaion step.
100%|████████████████████████████████████████████████| 305/305 [01:58<00:00,  2.58it/s]
  0%|                                                          | 0/305 [00:00<?, ?it/s]/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py:3302: UserWarning: 'kind' argument to argsort is ignored; only 'stable' sorts are supported.
  warnings.warn("'kind' argument to argsort is ignored; only 'stable' sorts "
  0%|                                                          | 0/305 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 341, in <module>
    test_loss, test_accuarcy, test_top_5_accuarcy = linear_unfreeze_eval_step(state, test_x, test_y)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 687, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 208, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 257, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 302, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2188, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2138, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "main.py", line 109, in linear_unfreeze_train_step
    top_5_accuracy = top_k(logits, y, 5)
  File "main.py", line 58, in top_k
    top_k_accuracy = np.mean(np.array([1 if y[k] in top_k else 0 for k in range(len(top_k))]))
  File "main.py", line 58, in <listcomp>
    top_k_accuracy = np.mean(np.array([1 if y[k] in top_k else 0 for k in range(len(top_k))]))
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 607, in __bool__
    def __bool__(self): return self.aval._bool(self)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1174, in error
    raise ConcretizationTypeError(arg, fname_context)
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[30])>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function.
The error occurred while tracing the function linear_unfreeze_train_step at main.py:97 for jit. This concrete value was not available in Python because it depends on the values of the arguments 'state', 'x', and 'y'.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "main.py", line 341, in <module>
    test_loss, test_accuarcy, test_top_5_accuarcy = linear_unfreeze_eval_step(state, test_x, test_y)
  File "main.py", line 109, in linear_unfreeze_train_step
    top_5_accuracy = top_k(logits, y, 5)
  File "main.py", line 58, in top_k
    top_k_accuracy = np.mean(np.array([1 if y[k] in top_k else 0 for k in range(len(top_k))]))
  File "main.py", line 58, in <listcomp>
    top_k_accuracy = np.mean(np.array([1 if y[k] in top_k else 0 for k in range(len(top_k))]))
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[30])>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function.
The error occurred while tracing the function linear_unfreeze_train_step at main.py:97 for jit. This concrete value was not available in Python because it depends on the values of the arguments 'state', 'x', and 'y'.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
Traceback (most recent call last):
  File "main.py", line 341, in <module>
    test_loss, test_accuarcy, test_top_5_accuarcy = linear_unfreeze_eval_step(state, test_x, test_y)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 687, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 208, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 257, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 302, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2188, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2138, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "main.py", line 109, in linear_unfreeze_train_step
    top_5_accuracy = top_k(logits, y, 5)
  File "main.py", line 58, in top_k
    top_k_accuracy = np.mean(np.array([1 if y[k] in top_k else 0 for k in range(len(top_k))]))
  File "main.py", line 58, in <listcomp>
    top_k_accuracy = np.mean(np.array([1 if y[k] in top_k else 0 for k in range(len(top_k))]))
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 607, in __bool__
    def __bool__(self): return self.aval._bool(self)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1174, in error
    raise ConcretizationTypeError(arg, fname_context)
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[30])>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function.
The error occurred while tracing the function linear_unfreeze_train_step at main.py:97 for jit. This concrete value was not available in Python because it depends on the values of the arguments 'state', 'x', and 'y'.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "main.py", line 341, in <module>
    test_loss, test_accuarcy, test_top_5_accuarcy = linear_unfreeze_eval_step(state, test_x, test_y)
  File "main.py", line 109, in linear_unfreeze_train_step
    top_5_accuracy = top_k(logits, y, 5)
  File "main.py", line 58, in top_k
    top_k_accuracy = np.mean(np.array([1 if y[k] in top_k else 0 for k in range(len(top_k))]))
  File "main.py", line 58, in <listcomp>
    top_k_accuracy = np.mean(np.array([1 if y[k] in top_k else 0 for k in range(len(top_k))]))
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[30])>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function.
The error occurred while tracing the function linear_unfreeze_train_step at main.py:97 for jit. This concrete value was not available in Python because it depends on the values of the arguments 'state', 'x', and 'y'.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError