
Loading dataset...
Loaded data : 93389
batch_size = 128
learning rate = 0.0001
train_size = 74711
test_size = 18678
Data load complete!
Initializing model....
Initialize complete!!
Epoch 1
Traceback (most recent call last):
  File "Conv1d_VAE_main.py", line 140, in <module>
    state, train_loss = train_step(state, x, rng)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 687, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 208, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 257, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 302, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2188, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2138, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "Conv1d_VAE_main.py", line 66, in train_step
    loss, grads = grad_fn(state.params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 1071, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 2516, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 133, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 122, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 802, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "Conv1d_VAE_main.py", line 58, in loss_fn
    recon_x, mean, logvar = Conv1d_CVAE().apply({'params': params['params']}, x, z_rng)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1183, in apply
    return apply(
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 865, in wrapper
    y = fn(root, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1586, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/anthonypark6904/module/Conv1d_model.py", line 107, in __call__
    mean, logvar = self.encoder(x)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/anthonypark6904/module/Conv1d_model.py", line 21, in __call__
    x = nn.normalization.BatchNorm(True)(x)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/normalization.py", line 251, in __call__
    ra_mean = self.variable('batch_stats', 'mean',
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 961, in variable
    v = self.scope.variable(col, name, init_fn, *init_args)
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 730, in variable
    raise errors.ScopeCollectionNotFound(col, name, self.path_text)
jax._src.traceback_util.UnfilteredStackTrace: flax.errors.ScopeCollectionNotFound: Tried to access "mean" from collection "batch_stats" in "/encoder/BatchNorm_0" but the collection is empty. (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeCollectionNotFound)
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "Conv1d_VAE_main.py", line 140, in <module>
    state, train_loss = train_step(state, x, rng)
  File "Conv1d_VAE_main.py", line 66, in train_step
    loss, grads = grad_fn(state.params)
  File "Conv1d_VAE_main.py", line 58, in loss_fn
    recon_x, mean, logvar = Conv1d_CVAE().apply({'params': params['params']}, x, z_rng)
  File "/home/anthonypark6904/module/Conv1d_model.py", line 107, in __call__
    mean, logvar = self.encoder(x)
  File "/home/anthonypark6904/module/Conv1d_model.py", line 21, in __call__
    x = nn.normalization.BatchNorm(True)(x)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/normalization.py", line 251, in __call__
    ra_mean = self.variable('batch_stats', 'mean',
flax.errors.ScopeCollectionNotFound: Tried to access "mean" from collection "batch_stats" in "/encoder/BatchNorm_0" but the collection is empty. (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeCollectionNotFound)
Traceback (most recent call last):
  File "Conv1d_VAE_main.py", line 140, in <module>
    state, train_loss = train_step(state, x, rng)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 687, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 208, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 257, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 302, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2188, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 2138, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "Conv1d_VAE_main.py", line 66, in train_step
    loss, grads = grad_fn(state.params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 1071, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 2516, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 133, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/ad.py", line 122, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/partial_eval.py", line 802, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "Conv1d_VAE_main.py", line 58, in loss_fn
    recon_x, mean, logvar = Conv1d_CVAE().apply({'params': params['params']}, x, z_rng)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1183, in apply
    return apply(
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 865, in wrapper
    y = fn(root, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1586, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/anthonypark6904/module/Conv1d_model.py", line 107, in __call__
    mean, logvar = self.encoder(x)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/anthonypark6904/module/Conv1d_model.py", line 21, in __call__
    x = nn.normalization.BatchNorm(True)(x)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/normalization.py", line 251, in __call__
    ra_mean = self.variable('batch_stats', 'mean',
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 961, in variable
    v = self.scope.variable(col, name, init_fn, *init_args)
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 730, in variable
    raise errors.ScopeCollectionNotFound(col, name, self.path_text)
jax._src.traceback_util.UnfilteredStackTrace: flax.errors.ScopeCollectionNotFound: Tried to access "mean" from collection "batch_stats" in "/encoder/BatchNorm_0" but the collection is empty. (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeCollectionNotFound)
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "Conv1d_VAE_main.py", line 140, in <module>
    state, train_loss = train_step(state, x, rng)
  File "Conv1d_VAE_main.py", line 66, in train_step
    loss, grads = grad_fn(state.params)
  File "Conv1d_VAE_main.py", line 58, in loss_fn
    recon_x, mean, logvar = Conv1d_CVAE().apply({'params': params['params']}, x, z_rng)
  File "/home/anthonypark6904/module/Conv1d_model.py", line 107, in __call__
    mean, logvar = self.encoder(x)
  File "/home/anthonypark6904/module/Conv1d_model.py", line 21, in __call__
    x = nn.normalization.BatchNorm(True)(x)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/normalization.py", line 251, in __call__
    ra_mean = self.variable('batch_stats', 'mean',
flax.errors.ScopeCollectionNotFound: Tried to access "mean" from collection "batch_stats" in "/encoder/BatchNorm_0" but the collection is empty. (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeCollectionNotFound)