
Loading dataset...
Loaded data : 62235
batch_size = 128
learning rate = 0.0001
train_size = 49788
test_size = 12447
Data load complete!
Initializing model....
Initialize complete!!
Epoch 1
CVAE_main.py:154: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "figsize" which is no longer supported as of 3.3 and will become an error in 3.6
  plt.savefig('recon.png', figsize=(16, 16))
CVAE_main.py:157: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "figsize" which is no longer supported as of 3.3 and will become an error in 3.6
  plt.savefig('x.png', figsize=(16, 16))

























epoch 1 - average loss - train : 45723.21875, test : 45801.296875562575
Epoch 2
























epoch 2 - average loss - train : 43566.2734375, test : 43692.4609375555
Epoch 3

























epoch 3 - average loss - train : 43506.39453125, test : 43608.039062525
Epoch 4

























epoch 4 - average loss - train : nan, test : nannn -inf42988.5390625755
Epoch 5



step : 46/389, train_loss : nan, test_loss : nan
Traceback (most recent call last):
  File "CVAE_main.py", line 140, in <module>
    x = (x / 100) + 1 # normalization : min = 0, max = 2
KeyboardInterrupt
Traceback (most recent call last):
  File "CVAE_main.py", line 140, in <module>
    x = (x / 100) + 1 # normalization : min = 0, max = 2
KeyboardInterrupt